/** IMPORTS */

/**
 * USE "import" :
 * - package.json => "type" : "module"
 * - server.js => import express from 'express'
 * 
 * Else : 
 * - server.js => const express = require('express')
*/

import express from 'express';

/**
 * Allow adding the appropriate CORS headers to all server responses. 
 * By default, CORS allows all origins to access server resources.
 */
import cors from 'cors';

/**
 * Logging tool used with Express.js to record information about 
 * incoming HTTP requests and the responses generated by the server
 */
import morgan from 'morgan';

/** Connection to the database */
import connect from './database/conn.js';

import router from './router/route.js'

const app = express();

/** MIDDLEWARES */

// Increased json data limit for profile images 
app.use(express.json({ limit: '5mb' }));
app.use(cors());
app.use(morgan('tiny'));
app.disable('x-powered-by') // less hackers know about ou stack

const port = 8080;

/** HTTP GET Request */
app.get('/', (req, res) => {
    res.status(201).json("Home GET Request");
});

/** API routes */
app.use('/api', router);




/** start server only whan we have valid connection*/
connect().then(() => {
    try {
        app.listen(port, () => {
            console.log(`Server connected tp http://localhost:${port}`);
        });
    } catch (error) {
        console.log('Cannot connect to the server')
    }
}).catch(error => {
    console.log("Invalid database connection...!")
});

